### ISSUE TITLE
After database restart, first db query always fails

### ISSUE THREAD

**Issue by m-bock** [nikita-volkov/hasql-pool#41]
I configured a connection pool with the following settings:

```
  Pool.acquire
      10
      (secondsToDiffTime 10000)
      (secondsToDiffTime 60000)
      (secondsToDiffTime 60000)
      dbSettings
```

If postgres service is running, everything works as expected. If I manually restart postgres service, the next DB query will always fail with a DB error. Subsequent requests will succeed. This is even the case if the configured timeouts (60s) are passed.

Is this expected behavior? I'd expect, that also the first request would succeed.

DB error is:
```
SessionUsageError 
  (QueryError
    "INSERT INTO ...."  
    (ResultError (ServerError "57P01" "terminating connection due to administrator command" Nothing Nothing Nothing)))
 ```

**Comment by nikita-volkov** [comment]
It is intentional. It provides you with an opportunity to handle such scenarios with some logic. However the logic may be something as simple as ignoring errors with status code "57P01". Without this error there would have been no mechanism for your application to know if a connection got closed for some reason when needed.

> This is even the case if the configured timeouts (60s) are passed.

It seems from your code that your timeouts are set to thousands of seconds.

BTW, you don't need any conversion functions to hardcode `DiffTime` values. E.g., the following should work:

```haskell
Pool.acquire 10 10 60 60 dbSettings
```

Pardon for slow response.
